# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mia's website
email: your-email@example.com
description: >-
  I'm a trans woman working in tech in the UK.
  Here is my experience dealing with various things in my life, from my career to my struggles with gender.
baseurl: "" # the sub path of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yorublaireau
github_username:  yorublaireau

# jekyll-paginate
paginate: 5
#paginate_path: "/blog/page:num/"

# Build settings
theme: jekyll-dash
plugins:
  - jekyll-feed
  - jekyll/tagging

exclude:
  - README.md
  - .idea/
   - Gemfile
   - Gemfile.lock

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

dash:
  # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # (optional) discqus comment configuration
  disqus:
    shortname: idontusedisqus

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # whether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: yorublaireau
  #avatar_source: local
  #avatar_path: /assets/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/Yorublaireau
      icon: twitter-square
      color: cyan
    - url: https://github.com/yorublaireau
      icon: github-square
      color: purple

  # whether the author box should be displayed or not
  show_author: true

google_analytics: G-Z2XYZZL9EM
